name: eikliw
favicon: null
layout_spectrum: 0.51042
typography_spectrum: 0.25409
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b5fda'
    - '#0b0b0b'
    - '#fdfdfd'
    - '#887832'
    - '#d1c1c1'
  brandStrength: 0.5
  lightness: 0.33845876436680555
  saturation: 0.6148773706518114
  rhythmicContrast: 0.5803353863302618
purpose: []
